apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: krapp-redis-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails-redis
  template:
    metadata:
      labels:
        app: rails-redis
    spec:
      containers:
        - name: krapp-redis
          image: redis:3.2.6
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
