apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: krapp-rails-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-puma
  template:
    metadata:
      labels:
        app: rails-puma
    spec:
      containers:
        - name: krapp-puma
          image: snkshukla/krapp:redis
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
